Cindy/image page ui merge
minhphu20/WinterCodeU pull request #45
Opened 2019-04-05 03:12 UTC by cindyxue

Finish UI implementation for the home page. Did not add any logic and event listener for buttons.

http://localhost:8080/image-page.html

2019-04-07 16:39 UTC, minhphu20 requested changes

2019-04-07 16:39 UTC, minhphu20 commented on src/main/webapp/image-page.html
> +    <style>
Why do we have a separate CSS file and this embedded style file. Perhaps merge them? :)

2019-04-08 22:52 UTC, jchau9 commented on src/main/webapp/css/ImagePage.css
> +    background-repeat:no-repeat;
background-repeat:no-repeat isn't necessary

2019-04-08 22:52 UTC, jchau9 commented on src/main/webapp/css/ImagePage.css
> +    background-repeat:no-repeat;
background-repeat:no-repeat isn't necessary

2019-04-08 22:53 UTC, jchau9 commented on src/main/webapp/css/ImagePage.css
> +    cursor:pointer;
add space -> cursor: pointer;

2019-04-08 22:53 UTC, jchau9 commented on src/main/webapp/css/ImagePage.css
> +    cursor:pointer;
add space -> cursor: pointer;

2019-04-09 03:40 UTC, jchau9 reviewed
Looks good!

2019-04-09 15:57 UTC, merged