Minh/like
minhphu20/WinterCodeU pull request #47
Opened 2019-04-08 06:10 UTC by minhphu20

Adding logic for like and not like images.

2019-04-09 02:12 UTC, cindyxue requested changes

2019-04-09 02:12 UTC, cindyxue commented on src/main/java/com/google/codeu/data/User.java
> +  public HashSet<String> getLikes() { return likes; }
Separate it to three lines to match styles with the other function

2019-04-09 02:12 UTC, cindyxue commented on src/main/java/com/google/codeu/data/User.java
> +  public HashSet<String> getNotLikes() { return notLikes; }
Separate it to three lines to match styles with the other function

2019-04-09 02:12 UTC, cindyxue commented on src/main/java/com/google/codeu/data/User.java
> +  public void addLike(String user) {
Make parameter name more specifically (eg. userEmail).

2019-04-09 02:12 UTC, cindyxue commented on src/main/java/com/google/codeu/data/User.java
> +  public void addNotLike(String user) {
Make parameter name more specifically (eg. userEmail).

2019-04-09 02:12 UTC, cindyxue commented on src/main/java/com/google/codeu/data/Datastore.java
> +    HashSet<String> likes = new HashSet<String>();
Is it better to initialize likes and dislikes hashset with null? Thus, we could distinguish if the user has likes or dislikes easily.

2019-04-14 07:37 UTC, minhphu20 commented
Archived as major code refractoring has been done in another pull :)

2019-04-14 07:38 UTC, closed without merging